version: "3.8"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "8390:8390"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
