export enum InfrastructureInjectionTokens {
	Template15MongoService = "Template15MongoService",
	WebSiteMockService = "WebSiteMockService",
	MysqlTemplate5Service = "MysqlTemplate5Service",
	MySqlTemplateRepository = "MySqlTemplateRepository",
	CreateTemplate15Command = "CreateTemplate15Command",
	FindTemplate15ByIdQuery = "FindTemplate15ByIdQuery",
	UpdateTemplate15Command = "UpdateTemplate15Command",
	DeleteTemplate15Command = "DeleteTemplate15Command",
	WebsiteMongooseService = "WebsiteMongooseService",
	CreateWebsiteCommand = "CreateWebsiteCommand",
	CheckDomainAvailabilityQuery = "CheckDomainAvailabilityQuery",
	CheckSubDomainAvailabilityQuery = "CheckSubDomainAvailabilityQuery",
	GetWebsitesByIdQuery = "GetWebsitesByIdQuery",
	CheckIfStoreHasMainWebSiteQuery = "CheckIfStoreHasMainWebSiteQuery",
	FindTemplateIdByCriteriaQuery = "FindTemplateIdByCriteriaQuery",
	GetWebsiteQuery = "GetWebsiteQuery",
	UpdateWebsiteCommand = "UpdateWebsiteCommand",
	FindTemplateRepoitoryQuery = "FindTemplateRepoitoryQuery",
	UpdateWebsiteSettingsCommand = "UpdateWebsiteSettingsCommand",
	DeleteWebsiteCommand = "DeleteWebsiteCommand",
	GetStoreTemplateSettingsQuery = "GetStoreTemplateSettingsQuery",
	GetStoreTemplateQuery = "GetStoreTemplateQuery"
}
