export enum InfrastructureInjectionTokens {
	OpenAIProducSuggetionsServices = "OpenAIProducSuggetionsServices",
	getProductDescriptionSuggestionsFromKeywordsQuery = "getProductDescriptionSuggestionsFromKeywordsQuery"
}
