export * from "./store-template-settings-repository"
export * from "./template5-repository"
export * from "./template6-repository"
export * from "./template15.repository"
export * from "./template99-repository"
export * from "./wapi-template.repository"
export * from "./websites.repository"
