export enum StorePaymentGateawayMethods {
	EPAYCO = "EPAYCO",
	PAYU = "PAYU",
	CREDIBANCO = "CREDIBANCO",
	WOMPI = "WOMPI",
	PAYMENTS_WAY = "PAYMENTS_WAY",
	WEPAY4U = "WEPAY4U",
	TU_COMPRA = "TU_COMPRA",
	FLOW = "FLOW",
	MERCADOPAGO = "MERCADOPAGO",
	ADDI = "ADDI",
	CASH_ON_DELIVERY = "CASH_ON_DELIVERY",
	PAYMENT_TO_BE_AGREED = "PAYMENT_TO_BE_AGREED",
	PICKUP_AND_PAY_IN_STORE = "PICKUP_AND_PAY_IN_STORE",
	BANK_CONSIGNMENT = "BANK_CONSIGNMENT",
	EFECTY = "EFECTY",
	NEQUI = "NEQUI",
	DAVIPLATA = "DAVIPLATA"
}
