export enum StorePaymentGateawayMethods {
	EPAYCO = "EPAYCO",
	PAYU = "PAYU",
	CREDIBANCO = "CREDIBANCO",
	WOMPI = "WOMPI",
	PAYMENTS_WAY = "PAYMENTS_WAY",
	WEPAY4U = "WEPAY4U",
	TU_COMPRA = "TU_COMPRA",
	ADDI = "ADDI"
}
