export enum StoresApplicationInjectionTokens {
	IStoreExternalApiRepository = "IStoreExternalApiRepository",
	IStoreDiscountRepository = "IStoreDiscountRepository",
	IStoreBlogRepository = "IStoreBlogRepository",
	IStoreCustomerAccessCodeRepository = "IStoreCustomerAccessCodeRepository",
	IStoreInfoRepository = "IStoreInfoRepository",
	IStoreProductCategoryRepository = "IStoreProductCategoryRepository",
	IStoreProductSubcategoryRepository = "IStoreProductSubcategoryRepository",
	IStoreGeolocationRepository = "IStoreGeolocationRepository",
	IStorePoliciesRepository = "IStorePoliciesRepository",
	IStoreBannerRepository = "IStoreBannerRepository",
	IStoreWhatsAppCheckoutRepository = "IStoreWhatsAppCheckoutRepository",
	IStoreEntitiesRepository = "IStoreEntitiesRepository",
	IStoreHeadquartersRepository = "IStoreHeadquartersRepository",
	IStoreShippingMeansRepository = "IStoreShippingMeansRepository",
	IStoreAnalyticsRepository = "IStoreAnalyticsRepository",
	IStroePaymentMethodsRepository = "IStroePaymentMethodsRepository",
	IStoreIntegrationsRepository = "IStoreIntegrationsRepository",
	IStoreLogoRepository = "IStoreLogoRepository"
}
